# Generated by Django 5.0.3 on 2024-03-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_cropimg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='rectangle',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='square',
            field=models.ImageField(upload_to=''),
        ),
    ]
