# Generated by Django 4.2.6 on 2024-03-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_cropimg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='y',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
