# Generated by Django 4.2.6 on 2024-03-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_cropimg', '0002_imageupload_height_imageupload_width_imageupload_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='height',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='width',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='x',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='y',
        ),
    ]
