# Generated by Django 4.2.6 on 2024-03-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_cropimg', '0003_remove_imageupload_height_remove_imageupload_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='upload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
