# Generated by Django 4.2.6 on 2024-03-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_cropimg', '0004_imageupload_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
