# Generated by Django 4.2.6 on 2024-03-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_cropimg', '0005_croppedimage_delete_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppedimage',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='croppedimage',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
